MODEL_ID = "Qwen/Qwen3-0.6B"
OUTPUT_DIR = "./checkpoints/qwen3-0.6b-cotpt"

NUM_HIDDEN_THOUGHT_TOKENS = 5

MAX_VISIBLE_TOKENS = 80
THINKING_TEMPERATURE = 0.8
THINKING_DO_SAMPLE = True
REAL_TOKEN_TEMPERATURE = 0.7
REAL_TOKEN_DO_SAMPLE = False
SHOW_HIDDEN_THOUGHTS = True

NUM_ROLLOUTS = 3
NUM_THINK_POSITIONS = 4
LOOKAHEAD = 4
THINK_TEMPERATURE = 1.0

BASE_LR = 5e-6
MIX_HEAD_LR = 1e-3
VALUE_HEAD_LR = 1e-3
AUX_LM_LOSS_WEIGHT = 1.0
REINFORCE_LOSS_WEIGHT = 1.0
MIX_LOSS_WEIGHT = 1.0
VALUE_LOSS_WEIGHT = 0.5
MAX_GRAD_NORM = 1.0

NUM_TRAINING_STEPS = 60
LOG_EVERY = 5
GRADIENT_ACCUMULATION_STEPS = 1

SEED = 42

NORMALIZE_REWARD = True
USE_VALUE_BASELINE = True
USE_KL_PENALTY = True
KL_COEFF = 0.05
USE_ENTROPY_BONUS = True
ENTROPY_COEFF = 0.01

# Quiet-STaR-faithful options (all default off for backward compatibility)
USE_THOUGHT_TOKENS = False
START_THOUGHT_TOKEN = "<|startofthought|>"
END_THOUGHT_TOKEN = "<|endofthought|>"
MIXING_MODE = "hidden"  # "hidden" (blend hiddens then lm_head) or "logit" (blend logits, Quiet-STaR)
USE_DIFFERENTIAL_REWARD = False
USE_POSITIVE_ONLY_REINFORCE = False

USE_LORA = False
LORA_R = 8
LORA_ALPHA = 16
LORA_DROPOUT = 0.0
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

USE_FROZEN_REFERENCE_WHEN_NO_LORA = True
